export const socketEmit = {
  ADD_FRIEND: 'ADD_FRIEND',
  ACCEPT_REQUEST: 'ACCEPT_REQUEST',
  UNFRIEND: 'UNFRIEND',
  TYPING: 'TYPING',
  CHANGE_ROOM_CHAT: 'CHANGE_ROOM_CHAT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  CREATE_GROUP: 'CREATE_GROUP',
};
